Frontends/Course.Web/Controllers/CoursesController.cs
using Course.Shared.Services;
using Course.Web.Models.Catalogs;
using Course.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Course.Web.Controllers
{
    [Authorize]
    public class CoursesController : Controller
    {
        private readonly ICatalogService _catalogService;
        private readonly ISharedIdentityService _sharedIdentityService;

        public CoursesController(ICatalogService catalogService, ISharedIdentityService sharedIdentityService)
        {
            _catalogService = catalogService;
            _sharedIdentityService = sharedIdentityService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _catalogService.GetAllCourseByUserIdAysnc(_sharedIdentityService.GetUserId));
        }

        public async Task<IActionResult> Create()
        {
            var categories = await _catalogService.GettAllCategoryAsync();
            ViewBag.categoryList = new SelectList(categories, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseCreateInput courseCreateInput)
        {
            var categories = await _catalogService.GettAllCategoryAsync();
            ViewBag.categoryList = new SelectList(categories, "Id", "Name");

            if (!ModelState.IsValid)
            {
                return View();
            }

            courseCreateInput.UserId = _sharedIdentityService.GetUserId;

            await _catalogService.CreateCourseAsync(courseCreateInput);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(string id)
        {
            var course = await _catalogService.GetByCourseIdAsync(id);
            var categories = await _catalogService.GettAllCategoryAsync();
            
            if (course == null)
            {
                RedirectToAction(nameof(Index));
            }

            ViewBag.categoryList = new SelectList(categories, "Id", "Name",course.Id);
            CourseUpdateInput courseUpdateInput = new()
            {
                Id = course.Id,
                Name = course.Name,
                Description = course.Description,
                Price = course.Price,
                Feature = course.Feature,
                CategoryId = course.CategoryId,
                UserId = course.UserId,
                Picture = course.Picture
            };

            return View(courseUpdateInput);
        }

        [HttpPost]
        public async Task<IActionResult> Update (CourseUpdateInput courseUpdateInput)
        {
            var categories = await _catalogService.GettAllCategoryAsync();
            ViewBag.categoryList = new SelectList(categories, "Id", "Name", courseUpdateInput.Id);

            if (!ModelState.IsValid)
            {
                return View();
            }

            await _catalogService.UpdateCourseAsync(courseUpdateInput);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Delete(string id)
        {
            await _catalogService.DeleteCourseAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Frontends/Course.Web/Views/Courses/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@model CourseCreateInput

<div class="row">
    <div class="col-md-8 offset-md-2">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Kurs Ekleme</h5>

                <form asp-controller="Courses" asp-action="Create" method="post" enctype="multipart/form-data">

                    <div asp-validation-summary="ModelOnly"></div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="CategoryId"></label>
                        <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.categoryList">
                            <option value="">kategori seçiniz</option>
                        </select>

                        <span class="text-danger" asp-validation-for="CategoryId"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="Name"></label>
                        <input class="form-control" asp-for="Name" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="Price"></label>
                        <input class="form-control" asp-for="Price" />
                        <span class="text-danger" asp-validation-for="Price"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="Description"></label>
                        <textarea class="form-control" asp-for="Description"></textarea>
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="Feature.Duration"></label>
                        <input class="form-control" asp-for="Feature.Duration" />
                        <span class="text-danger" asp-validation-for="Feature.Duration"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="PhotoFormFile"></label>
                        <input  class="form-control" type="file"  asp-for="PhotoFormFile"/>
                    </div>

                    <button type="submit" class="btn btn-primary">Kurs Kaydet</button>
                </form>
            </div>
        </div>

    </div>
</div>

Frontends/Course.Web/Views/Courses/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<CourseViewModel>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Kurslar</h5>
                
                <a asp-controller="Courses" asp-action="Create" class="btn btn-primary mb-3">Kurs Oluştur</a>

                @if (Model.Any())
                {
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Resim</th>
                                <th>Kurs Adı</th>
                                <th>Fiyat</th>
                                <th>Süresi</th>
                                <th>Kategori</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><img style="width:72px;" src="@item.StockPictureUrl" class="img-thumbnail"/></td>
                                    <td>@item.Name</td>
                                    <td>@item.Price</td>
                                    <td>@item.Feature.Duration</td>
                                    <td>@item.Category.Name</td>
                                    <td>
                                        <a asp-controller="Courses" asp-action="Update" asp-route-id="@item.Id" class="btn btn-success btn-sm">Güncelle</a>
                                        <a asp-controller="Courses" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Sil</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-info">
                        Kayıtlı Kurs Bulunamadı!
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Frontends/Course.Web/Views/Courses/Update.cshtml
@{
    ViewData["Title"] = "Update";
}
@model CourseUpdateInput

<div class="row">
    <div class="col-md-8 offset-md-2">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Kurs Güncelleme</h5>

                <form asp-controller="Courses" asp-action="Update" method="post" enctype="multipart/form-data">

                    <div asp-validation-summary="ModelOnly"></div>
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="UserId" />
                    <input type="hidden" asp-for="Picture" />

                    <div class="mb-3">
                        <label class="form-label" asp-for="CategoryId"></label>
                        <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.categoryList"></select>

                        <span class="text-danger" asp-validation-for="CategoryId"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="Name"></label>
                        <input class="form-control" asp-for="Name" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="Price"></label>
                        <input class="form-control" asp-for="Price" />
                        <span class="text-danger" asp-validation-for="Price"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="Description"></label>
                        <textarea class="form-control" asp-for="Description"></textarea>
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="Feature.Duration"></label>
                        <input class="form-control" asp-for="Feature.Duration" />
                        <span class="text-danger" asp-validation-for="Feature.Duration"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="PhotoFormFile"></label>
                        <input class="form-control" type="file" asp-for="PhotoFormFile" />
                    </div>

                    <button type="submit" class="btn btn-primary">Kurs Güncelle</button>
                </form>
            </div>
        </div>

    </div>
</div>